# Generated by Django 4.1.5 on 2023-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancebot',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
